apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    orgid: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
  - name: Prometheus
    type: prometheus
    access: proxy
    orgid: 1
    url: http://prometheus:9090/prometheus
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
