apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgid: 1
    url: http://prometheus:9090/prometheus
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
