//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaCS.Presentation.MAUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaCS.Presentation.MAUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administrating {
            get {
                return ResourceManager.GetString("Administrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked:.
        /// </summary>
        internal static string Booked {
            get {
                return ResourceManager.GetString("Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        internal static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel booking.
        /// </summary>
        internal static string BookingCancel {
            get {
                return ResourceManager.GetString("BookingCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save the changes?.
        /// </summary>
        internal static string ChangesAsking {
            get {
                return ResourceManager.GetString("ChangesAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this workspace? You will not be able to restore it after deletion.
        /// </summary>
        internal static string ChangesDeleting {
            get {
                return ResourceManager.GetString("ChangesDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm booking information:.
        /// </summary>
        internal static string ConfirmBookingData {
            get {
                return ResourceManager.GetString("ConfirmBookingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm cancellation.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string ConfirmChanges {
            get {
                return ResourceManager.GetString("ConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm creation.
        /// </summary>
        internal static string ConfrimCreate {
            get {
                return ResourceManager.GetString("ConfrimCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and account.
        /// </summary>
        internal static string DeleteAndLogOut {
            get {
                return ResourceManager.GetString("DeleteAndLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment:.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {} options.
        /// </summary>
        internal static string FoundedNSequences {
            get {
                return ResourceManager.GetString("FoundedNSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking journal.
        /// </summary>
        internal static string JournalBooking {
            get {
                return ResourceManager.GetString("JournalBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meeting room.
        /// </summary>
        internal static string MeetingRoom {
            get {
                return ResourceManager.GetString("MeetingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found! Try changing your query.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create office.
        /// </summary>
        internal static string OfficeCreate {
            get {
                return ResourceManager.GetString("OfficeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office creation.
        /// </summary>
        internal static string OfficeCreating {
            get {
                return ResourceManager.GetString("OfficeCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office editing.
        /// </summary>
        internal static string OfficeRedacting {
            get {
                return ResourceManager.GetString("OfficeRedacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        internal static string Offices {
            get {
                return ResourceManager.GetString("Offices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time:.
        /// </summary>
        internal static string PickTime {
            get {
                return ResourceManager.GetString("PickTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create place.
        /// </summary>
        internal static string PlaceCreate {
            get {
                return ResourceManager.GetString("PlaceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete place.
        /// </summary>
        internal static string PlaceDelete {
            get {
                return ResourceManager.GetString("PlaceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this workspace? You will not be able to restore it after deletion.
        /// </summary>
        internal static string PlaceDeleting {
            get {
                return ResourceManager.GetString("PlaceDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places in this office.
        /// </summary>
        internal static string PlacesInOffice {
            get {
                return ResourceManager.GetString("PlacesInOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place type.
        /// </summary>
        internal static string PlaceType {
            get {
                return ResourceManager.GetString("PlaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking a coworking space.
        /// </summary>
        internal static string Promo {
            get {
                return ResourceManager.GetString("Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place type.
        /// </summary>
        internal static string ResourceType {
            get {
                return ResourceManager.GetString("ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search target.
        /// </summary>
        internal static string SearchTarget {
            get {
                return ResourceManager.GetString("SearchTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Succes {
            get {
                return ResourceManager.GetString("Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unspecified.
        /// </summary>
        internal static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the coworking space booking system!.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work place.
        /// </summary>
        internal static string WorkPlace {
            get {
                return ResourceManager.GetString("WorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account.
        /// </summary>
        internal static string YourAccount {
            get {
                return ResourceManager.GetString("YourAccount", resourceCulture);
            }
        }
    }
}
