services:
  bacs.api:
    build:
      context: .
      dockerfile: Source/Presentation/BaCS.Presentation.API/Dockerfile
    ports:
      - "8080:8080"
  postgres:
    ports:
      - "5432:5432"
  jaeger:
    ports:
      - "16686:16686"
      - "4317:4317"
  grafana:
    ports:
      - "3000:3000"
  prometheus:
    ports:
      - "9090:9090"
  seq:
    ports:
      - "80:80"
      - "5341:5341"
  minio:
    ports:
      - '9000:9000'
      - '9001:9001'
  cadvisor:
    ports:
      - "8090:8080"
  keycloak:
    ports:
      - "7080:7080"
      - "7443:7443"
