services:
  bacs.api:
    image: bacs.api
    container_name: bacs.api
    build:
      context: .
      dockerfile: Source/Presentation/BaCS.Presentation.API/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      PostgresOptions__Username: ${BACS_PG_USER}
      PostgresOptions__Password: ${BACS_PG_PASSWORD}
      PostgresOptions__Host: ${BACS_PG_HOST}
      PostgresOptions__Port: ${BACS_PG_PORT}
      PostgresOptions__Database: ${BACS_PG_DATABASE}
      PostgresOptions__Schema: ${BACS_PG_SCHEMA}
      PostgresOptions__AdditionalProperties: ${BACS_PG_ADDITIONAL_PROPERTIES}
    ports:
      - "8080:8080" # for development
    depends_on:
      - postgres
    networks:
      - bacs

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # for development
    networks:
      - bacs
    volumes:
      - pg_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      QUERY_BASE_PATH: "/jaeger"
    ports:
      - "16686:16686"
    networks:
      - bacs

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./.deployment/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - bacs

  loki:
    container_name: loki
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bacs

  promtail:
    container_name: proomtail
    image: grafana/promtail
    volumes:
      - /var/log/:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - bacs

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prom_data:/prometheus
      - ./.deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bacs

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bacs

volumes:
  pg_data:
  grafana_data:
  prom_data:

networks:
  bacs:
    driver: bridge
