services:
  bacs.api:
    image: ${BACS_IMAGE:-bacs.api}
    container_name: bacs.api
    platform: ${BACS_PLATFORM}
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      PostgresOptions__Username: ${BACS_PG_USER}
      PostgresOptions__Password: ${BACS_PG_PASSWORD}
      PostgresOptions__Host: ${BACS_PG_HOST}
      PostgresOptions__Port: ${BACS_PG_PORT}
      PostgresOptions__Database: ${BACS_PG_DATABASE}
      PostgresOptions__Schema: ${BACS_PG_SCHEMA}
      PostgresOptions__AdditionalProperties: ${BACS_PG_ADDITIONAL_PROPERTIES}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - bacs

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bacs
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      QUERY_BASE_PATH: "/jaeger"
    networks:
      - bacs

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      # ./grafana_data must have 0777 permission mode
      - ./grafana_data:/var/lib/grafana
      - ./grafana_data/plugins:/var/lib/grafana/plugins
      - ./.deployment/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./.deployment/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    user: ${GF_USER_ID} # 0 for root or other for custom user
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    networks:
      - bacs

  loki:
    image: grafana/loki
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bacs

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prom_data:/prometheus
      - ./.deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=/prometheus/"
    networks:
      - bacs

  nginx-proxy:
    image: nginx:1.27.4-alpine-slim
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_CERTS_FULLCHAIN_PATH}:/etc/nginx/certs/fullchain.pem:ro
      - ${NGINX_PRIVKEY_PATH}:/etc/nginx/certs/privkey.pem:ro
      - ./.deployment/nginx/templates:/etc/nginx/templates/:ro
      - ./.deployment/nginx/index.html:/usr/share/nginx/html/index.html:ro
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
    networks:
      - bacs

volumes:
  pg_data:
  grafana_data:
  prom_data:

networks:
  bacs:
    driver: bridge
