{
 "title": "ASP.NET Endpoints",
 "description": "ASP.NET endpoint metrics from Prometheus.net",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(microsoft_aspnetcore_hosting_total_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket{job=\"$job\"},instance)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket,endpoint)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket{endpoint=~\"$route\"},method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration - $method $route",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate - $method $route",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\", http_response_status_code=~\"4..|5..\"}[$__rate_interval]) or vector(0)) / sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(le) (\n  rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{\n    job=\"$job\",\n    instance=\"$instance\",\n    http_route=~\"$route\",\n    http_request_method=~\"$method\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhandled Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (error_type) (\r\n  ceil(increase(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\", error_type!=\"\"}[$__range]))\r\n)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n    ceil(increase(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__range]))\r\n  )",
     "legendFormat": "Status {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Secured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    ceil(increase(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__range]))\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(ceil(increase(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"$job\", instance=\"$instance\", http_route=~\"$route\", http_request_method=~\"$method\"}[$__range])), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  }
 ]
}